version: '3.8'
services:
  api:
    build: .
    container_name: online-shopping-mall-clone-client-frontend
    ports:
      - '2022:3000'
    volumes:
      - /app
      - /app/node_modules
    stdin_open: true
    tty: true 